# Generated by Django 2.0 on 2017-12-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171214_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='potrait_id',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
