# Generated by Django 2.0 on 2017-12-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_snippet_potrait_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='potrait_id',
            new_name='portrait_id',
        ),
    ]
